server:
  port: 4444

#spring:
 # cloud:
  #  config:
   #   server:
    #    git:
     #     uri: https://github.com/AmaruAtreides/confiles
      #    username: AmaruAtreides
       #   password: Ragnar0k.1701
        #  force-pull: true
         # skipSslValidation: true
