server:
  port: 4444

#spring:
 # cloud:
  #  config:
   #   server:
    #    git:
     #     uri: 
      #    username: 
       #   password: 
        #  force-pull: true
         # skipSslValidation: true
